# Generated by Django 2.2.4 on 2019-09-17 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
