# Generated by Django 2.2.4 on 2019-09-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_tag_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='question',
        ),
    ]
