# Generated by Django 2.2.4 on 2019-09-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_tag_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='active',
            new_name='is_active',
        ),
    ]
